//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// This partial class was auto-generated for use with the Habanero Architecture.
// NB Custom code should be placed in the provided stub class.
// Please do not modify this class directly!
// ------------------------------------------------------------------------------

namespace Invoicing.BO
{
    using System;
    using Habanero.BO;
    
    
    public partial class InvoiceLine : BusinessObject
    {
        
        #region Properties       
        public virtual Guid? InvoiceLineID
        {
            get
            {
                return ((Guid?)(base.GetPropertyValue("InvoiceLineID")));
            }
            set
            {
                base.SetPropertyValue("InvoiceLineID", value);
            }
        }
        
        public virtual Guid? InvoiceID
        {
            get
            {
                return ((Guid?)(base.GetPropertyValue("InvoiceID")));
            }
            set
            {
                base.SetPropertyValue("InvoiceID", value);
            }
        }
        
        public virtual String InvoiceLineNumber
        {
            get
            {
                return ((String)(base.GetPropertyValue("InvoiceLineNumber")));
            }
            set
            {
                base.SetPropertyValue("InvoiceLineNumber", value);
            }
        }
        public virtual Decimal? InvoiceLineValue
        {
            get
            {
                return ((Decimal?)(base.GetPropertyValue("InvoiceLineValue")));
            }
            set
            {
                base.SetPropertyValue("InvoiceLineValue", value);
            }
        }
        #endregion
        
        #region Relationships
        public virtual Invoice Invoice
        {
            get
            {
                return Relationships.GetRelatedObject<Invoice>("Invoice");
            }
            set
            {
                Relationships.SetRelatedObject("Invoice", value);
            }
        }
        #endregion
    }
}
