using System;

namespace Habanero.Base
{
    ///<summary>
    /// Represents the method that will handle an event.
    ///</summary>
    ///<param name="sender">The source of the event.</param>
    ///<param name="eventArgs1">A <see cref="TEventArgs1"/> that contains the event data.</param>
    ///<param name="eventArgs2">A <see cref="TEventArgs2"/> that contains the event data.</param>
    ///<typeparam name="TEventArgs1">The type of the event data generated by the event for the first parameter.</typeparam>
    ///<typeparam name="TEventArgs2">The type of the event data generated by the event for the second parameter.</typeparam>
    public delegate void EventHandler<TEventArgs1, TEventArgs2>(object sender, TEventArgs1 eventArgs1, TEventArgs2 eventArgs2)
        where TEventArgs1 : EventArgs 
        where TEventArgs2 : EventArgs;
}