//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habanero.Bo.Loaders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dtds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dtds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Habanero.Bo.Loaders.Dtds", typeof(Dtds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include key.dtd
        ///#include PrimaryKeyDef.dtd
        ///#include property.dtd
        ///#include RelationshipDef.dtd
        ///#include superClass.dtd
        ///#include UIDef.dtd
        ///&lt;!ELEMENT class (superClass?, property*, key*, primaryKeyDef?, relationshipDef*, uiDef*)&gt;
        ///&lt;!ATTLIST class
        ///		name NMTOKEN #REQUIRED
        ///		assembly NMTOKEN #REQUIRED
        ///		table NMTOKEN #IMPLIED
        ///&gt;
        ///
        ///.
        /// </summary>
        internal static string _class {
            get {
                return ResourceManager.GetString("_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT businessObjectLookupList EMPTY&gt;
        ///&lt;!ATTLIST businessObjectLookupList 
        ///	class NMTOKEN #REQUIRED
        ///	assembly NMTOKEN #REQUIRED
        ///&gt;.
        /// </summary>
        internal static string businessObjectLookupList {
            get {
                return ResourceManager.GetString("businessObjectLookupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include class.dtd
        ///&lt;!ELEMENT classes (class+)&gt;
        ///.
        /// </summary>
        internal static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT databaseLookupList EMPTY&gt;
        ///&lt;!ATTLIST databaseLookupList
        ///	sql CDATA #REQUIRED
        ///	class NMTOKEN #IMPLIED
        ///	assembly NMTOKEN #IMPLIED
        ///&gt;.
        /// </summary>
        internal static string databaseLookupList {
            get {
                return ResourceManager.GetString("databaseLookupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include GridProperty.dtd
        ///&lt;!ELEMENT gridPropertyCollection (gridProperty+)&gt;
        ///&lt;!ATTLIST gridPropertyCollection
        ///	name NMTOKEN #REQUIRED
        ///&gt;.
        /// </summary>
        internal static string GridPropertyCollection {
            get {
                return ResourceManager.GetString("GridPropertyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include Prop.dtd
        ///&lt;!ELEMENT key (prop+)&gt;
        ///&lt;!ATTLIST key 
        ///	name NMTOKEN #IMPLIED
        ///	ignoreIfNull ( true | false ) &quot;false&quot;
        ///&gt;
        ///.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include Prop.dtd
        ///&lt;!ELEMENT primaryKey (prop+)&gt;
        ///&lt;!ATTLIST primaryKey 
        ///	isObjectID ( true | false ) &quot;true&quot;
        ///&gt;
        ///.
        /// </summary>
        internal static string primaryKey {
            get {
                return ResourceManager.GetString("primaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT prop EMPTY&gt;
        ///&lt;!ATTLIST prop
        ///	name NMTOKEN #REQUIRED
        ///&gt;.
        /// </summary>
        internal static string Prop {
            get {
                return ResourceManager.GetString("Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include rule.dtd
        ///#include databaseLookupList.dtd
        ///#include simpleLookupList.dtd
        ///#include businessObjectLookupList.dtd
        ///&lt;!ELEMENT property (rule*, databaseLookupList*, simpleLookupList*, businessObjectLookupList*)&gt;
        ///&lt;!ATTLIST property
        ///	name NMTOKEN #REQUIRED
        ///	type NMTOKEN &quot;String&quot;
        ///	assembly NMTOKEN &quot;System&quot;
        ///	readWriteRule (	ReadWrite | ReadOnly | WriteOnce ) &quot;ReadWrite&quot;
        ///	databaseField CDATA #IMPLIED
        ///	default CDATA #IMPLIED
        ///  compulsory ( true | false ) &quot;false&quot;
        ///&gt;
        ///.
        /// </summary>
        internal static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT relationshipDef (relKeyDef)&gt;
        ///&lt;!ATTLIST relationshipDef
        ///	name NMTOKEN #REQUIRED
        ///	type (single | multiple) #REQUIRED
        ///	relatedType NMTOKEN #REQUIRED
        ///	relatedAssembly	NMTOKEN #REQUIRED
        ///	keepReferenceToRelatedObject ( true | false ) &quot;true&quot;
        ///	orderBy CDATA &quot;&quot;
        ///	minNoOfRelatedObjects NMTOKEN &quot;0&quot;
        ///	maxNoOfRelatedObjects NMTOKEN &quot;-1&quot;
        ///	deleteParentAction ( DeleteRelatedObjects | DereferenceRelatedObjects | PreventDeleteParent ) &quot;PreventDeleteParent&quot;
        ///&gt;
        ///	&lt;!ELEMENT relKeyDef (relProp+)&gt;
        ///		&lt;!ELEMENT r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelationshipDef {
            get {
                return ResourceManager.GetString("RelationshipDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT add EMPTY&gt;
        ///&lt;!ATTLIST add
        ///	key NMTOKEN #REQUIRED
        ///  value CDATA #REQUIRED
        ///&gt;
        ///&lt;!ELEMENT rule (add*)&gt;
        ///&lt;!ATTLIST rule
        ///	name NMTOKEN #REQUIRED
        ///	class NMTOKEN #IMPLIED
        ///  assembly NMTOKEN #IMPLIED
        ///  message CDATA #IMPLIED
        ///&gt;.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT simpleLookupList (stringGuidPair*)&gt;
        ///&lt;!ELEMENT stringGuidPair EMPTY&gt;
        ///&lt;!ATTLIST stringGuidPair
        ///	string CDATA #REQUIRED
        ///	guid   CDATA #REQUIRED
        ///&gt;
        ///.
        /// </summary>
        internal static string simpleLookupList {
            get {
                return ResourceManager.GetString("simpleLookupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT superClass EMPTY&gt;
        ///&lt;!ATTLIST superClass
        ///		class NMTOKEN #REQUIRED
        ///		assembly NMTOKEN #REQUIRED
        ///		orMapping ( ClassTableInheritance | SingleTableInheritance | ConcreteTableInheritance ) &quot;ClassTableInheritance&quot;
        ///&gt;.
        /// </summary>
        internal static string superClass {
            get {
                return ResourceManager.GetString("superClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include UIGridDef.dtd
        ///#include UIFormDef.dtd
        ///&lt;!ELEMENT uiDef (uiGridDef?, uiFormDef?)&gt;
        ///&lt;!ATTLIST uiDef
        ///	name NMTOKEN &quot;default&quot;
        ///&gt;.
        /// </summary>
        internal static string UIDef {
            get {
                return ResourceManager.GetString("UIDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include UIFormProperty.dtd
        ///&lt;!ELEMENT uiFormColumn (uiFormProperty+)&gt;
        ///&lt;!ATTLIST uiFormColumn
        ///	width CDATA &quot;-1&quot;
        ///&gt;
        ///.
        /// </summary>
        internal static string UIFormColumn {
            get {
                return ResourceManager.GetString("UIFormColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include UIFormTab.dtd
        ///&lt;!ELEMENT uiFormDef (uiFormTab+)&gt;
        ///&lt;!ATTLIST uiFormDef
        ///	width CDATA &quot;-1&quot;
        ///	height CDATA &quot;-1&quot;
        ///	heading CDATA &quot;&quot;
        ///&gt;
        ///.
        /// </summary>
        internal static string UIFormDef {
            get {
                return ResourceManager.GetString("UIFormDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT uiFormGrid EMPTY&gt;
        ///&lt;!ATTLIST uiFormGrid
        ///	relationshipName NMTOKEN #REQUIRED
        ///	gridType NMTOKEN &quot;Habanero.Ui.Grid.SimpleGrid&quot;
        ///	gridTypeAssembly NMTOKEN &quot;Habanero.UI.Pro&quot;
        ///	correspondingRelationshipName NMTOKEN #REQUIRED
        ///&gt;.
        /// </summary>
        internal static string UIFormGrid {
            get {
                return ResourceManager.GetString("UIFormGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include UIFormPropertyAtt.dtd
        ///&lt;!ELEMENT uiFormProperty (uiFormPropertyAtt*)&gt;
        ///&lt;!ATTLIST uiFormProperty
        ///	label CDATA #REQUIRED
        ///	propertyName NMTOKEN #REQUIRED
        ///	controlTypeName NMTOKEN	&quot;TextBox&quot;
        ///	controlAssemblyName NMTOKEN &quot;System.Windows.Forms&quot;
        ///	mapperTypeName NMTOKEN &quot;TextBoxMapper&quot;
        ///	isReadOnly ( true | false ) &quot;false&quot;
        ///&gt;.
        /// </summary>
        internal static string UIFormProperty {
            get {
                return ResourceManager.GetString("UIFormProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT uiFormPropertyAtt EMPTY&gt;
        ///&lt;!ATTLIST uiFormPropertyAtt
        ///	name NMTOKEN #REQUIRED
        ///	value CDATA #REQUIRED
        ///&gt;.
        /// </summary>
        internal static string UIFormPropertyAtt {
            get {
                return ResourceManager.GetString("UIFormPropertyAtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include UIFormColumn.dtd
        ///#include UIFormGrid.dtd
        ///&lt;!ELEMENT uiFormTab (uiFormGrid*, uiFormColumn*)&gt;
        ///&lt;!ATTLIST uiFormTab
        ///	name CDATA #REQUIRED
        ///&gt;
        ///.
        /// </summary>
        internal static string UIFormTab {
            get {
                return ResourceManager.GetString("UIFormTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include UIGridProperty.dtd
        ///&lt;!ELEMENT uiGridDef (uiGridProperty+)&gt;.
        /// </summary>
        internal static string UIGridDef {
            get {
                return ResourceManager.GetString("UIGridDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!ELEMENT uiGridProperty EMPTY&gt;
        ///&lt;!ATTLIST uiGridProperty
        ///	heading CDATA #REQUIRED
        ///	propertyName CDATA #REQUIRED
        ///	gridControlTypeName NMTOKEN	&quot;DataGridViewTextBoxColumn&quot;
        ///	isReadOnly ( true | false ) &quot;false&quot;
        ///	width CDATA &quot;100&quot;
        ///	alignment ( left | right | center | centre ) &quot;left&quot;
        ///&gt;.
        /// </summary>
        internal static string UIGridProperty {
            get {
                return ResourceManager.GetString("UIGridProperty", resourceCulture);
            }
        }
    }
}
