//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// This partial class was auto-generated for use with the Habanero Architecture.
// NB Custom code should be placed in the provided stub class.
// Please do not modify this class directly!
// ------------------------------------------------------------------------------

using System;

namespace Habanero.Test.Structure
{
    public partial class Car : Vehicle
    {
        
        #region Properties
        public virtual Guid? CarID
        {
            get
            {
                return ((Guid?)(base.GetPropertyValue("CarID")));
            }
            set
            {
                base.SetPropertyValue("CarID", value);
            }
        }
        
        public virtual String RegistrationNo
        {
            get
            {
                return ((String)(base.GetPropertyValue("RegistrationNo")));
            }
            set
            {
                base.SetPropertyValue("RegistrationNo", value);
            }
        }
        
        public virtual Double? Length
        {
            get
            {
                return ((Double?)(base.GetPropertyValue("Length")));
            }
            set
            {
                base.SetPropertyValue("Length", value);
            }
        }
        
        public virtual Boolean? IsConvertible
        {
            get
            {
                return ((Boolean?)(base.GetPropertyValue("IsConvertible")));
            }
            set
            {
                base.SetPropertyValue("IsConvertible", value);
            }
        }
        
        public virtual Guid? DriverID
        {
            get
            {
                return ((Guid?)(base.GetPropertyValue("DriverID")));
            }
            set
            {
                base.SetPropertyValue("DriverID", value);
            }
        }
        #endregion
        
        #region Relationships
        public virtual Person Driver
        {
            get
            {
                return Relationships.GetRelatedObject<Person>("Driver");
            }
            set
            {
                Relationships.SetRelatedObject("Driver", value);
            }
        }
        #endregion
    }
}