//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// This partial class was auto-generated for use with the Habanero Architecture.
// NB Custom code should be placed in the provided stub class.
// Please do not modify this class directly!
// ------------------------------------------------------------------------------

namespace Habanero.Test.Structure.BO
{
    using System;
    using Habanero.BO;
    using Habanero.Test.Structure.BO;
    
    
    public partial class Organisation : LegalEntity
    {
        
        #region Properties
        public virtual String Name
        {
            get
            {
                return ((String)(base.GetPropertyValue("Name")));
            }
            set
            {
                base.SetPropertyValue("Name", value);
            }
        }
        
        public virtual String DateFormed
        {
            get
            {
                return ((String)(base.GetPropertyValue("DateFormed")));
            }
            set
            {
                base.SetPropertyValue("DateFormed", value);
            }
        }
        
        public virtual Guid? OrganisationID
        {
            get
            {
                return ((Guid?)(base.GetPropertyValue("OrganisationID")));
            }
            set
            {
                base.SetPropertyValue("OrganisationID", value);
            }
        }
        #endregion
        
        #region Relationships
        public virtual BusinessObjectCollection<OrganisatiionPerson> OrganisationPerson
        {
            get
            {
                return Relationships.GetRelatedCollection<OrganisatiionPerson>("OrganisationPerson");
            }
        }
        #endregion
    }
}
