//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// This partial class was auto-generated for use with the Habanero Architecture.
// NB Custom code should be placed in the provided stub class.
// Please do not modify this class directly!
// ------------------------------------------------------------------------------

namespace Habanero.Test.Structure.BO
{
    using System;
    using Habanero.BO;
    using Habanero.Test.Structure.BO;
    
    
    public partial class Person : LegalEntity
    {
        
        #region Properties
        public virtual String IDNumber
        {
            get
            {
                return ((String)(base.GetPropertyValue("IDNumber")));
            }
            set
            {
                base.SetPropertyValue("IDNumber", value);
            }
        }
        
        public virtual String FirstName
        {
            get
            {
                return ((String)(base.GetPropertyValue("FirstName")));
            }
            set
            {
                base.SetPropertyValue("FirstName", value);
            }
        }
        
        public virtual String LastName
        {
            get
            {
                return ((String)(base.GetPropertyValue("LastName")));
            }
            set
            {
                base.SetPropertyValue("LastName", value);
            }
        }
        
        public virtual String PersonID
        {
            get
            {
                return ((String)(base.GetPropertyValue("PersonID")));
            }
            set
            {
                base.SetPropertyValue("PersonID", value);
            }
        }
        #endregion
        
        #region Relationships
        public virtual BusinessObjectCollection<Car> CarsDriven
        {
            get
            {
                return Relationships.GetRelatedCollection<Car>("CarsDriven");
            }
        }
        
        public virtual BusinessObjectCollection<OrganisatiionPerson> OrganisationPerson
        {
            get
            {
                return Relationships.GetRelatedCollection<OrganisatiionPerson>("OrganisationPerson");
            }
        }
        #endregion
    }
}
